[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crawler"
version = "0.1.1"
dependencies = [
]

[project.scripts]
crawler = "crawler.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
